### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by generalbigsur** [xiezhy6/PASTA-GAN-plusplus#1]
Hello, Great work! The results in the paper look very impressive. Could you please provide instructions on how to run this code? Also, could you provide the links to images in the dataset and instructions to do any preprocessing? Thank you very much!

**Comment by xiezhy6** [comment]
Sure, we will add a readme about the instruction this weekend :-)

**Comment by niranjan-v** [comment]
Hi, Thanks a lot for providing the code. Could you kindly confirm which package has been used to generate the garment parsing inputs in the test_datas? This would help to train and test the method on custom data. Thanks!

**Comment by generalbigsur** [comment]
+1. Yeah, a section on "data preparation" similar to one in the [PASTA-GAN repo](https://github.com/xiezhy6/PASTA-GAN-) would be really helpful. Please consider adding that too. Thank you very much!

**Comment by xiezhy6** [comment]
> Hi, Thanks a lot for providing the code. Could you kindly confirm which package has been used to generate the garment parsing inputs in the test_datas? This would help to train and test the method on custom data. Thanks!

Hi, like our previous work PASTA-GAN, the sleeve mask is not a necessary input for the model training and testing. I will update the codebase to make the garment parsing an optional input for the model training and testing. :-)

**Comment by buptpriswang** [comment]
Thanks a lot for providing the code! But I got the following error when I run the code.
Loading networks from "./ckpt/network-snapshot-004408.pkl"...
Loading custom kernel...
Traceback (most recent call last):
  File "test.py", line 190, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/qinlong.wang/anaconda3/envs/pasta37/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/qinlong.wang/anaconda3/envs/pasta37/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/qinlong.wang/anaconda3/envs/pasta37/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qinlong.wang/anaconda3/envs/pasta37/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/qinlong.wang/anaconda3/envs/pasta37/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "test.py", line 103, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "/home/qinlong.wang/exp/virtual_try_on/PASTA-GAN-plusplus/legacy.py", line 21, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/home/qinlong.wang/exp/virtual_try_on/PASTA-GAN-plusplus/torch_utils/persistence.py", line 191, in _reconstruct_persistent_obj
    module = _src_to_module(meta.module_src)
  File "/home/qinlong.wang/exp/virtual_try_on/PASTA-GAN-plusplus/torch_utils/persistence.py", line 227, in _src_to_module
    exec(src, module.__dict__) # pylint: disable=exec-used
  File "<string>", line 2282, in <module>
NameError: name 'os' is not defined

**Comment by buptpriswang** [comment]
> > Hi, Thanks a lot for providing the code. Could you kindly confirm which package has been used to generate the garment parsing inputs in the test_datas? This would help to train and test the method on custom data. Thanks!
> 
> Hi, like our previous work PASTA-GAN, the sleeve mask is not a necessary input for the model training and testing. I will update the codebase to make the garment parsing an optional input for the model training and testing. :-)

hello, is there any update about this?

**Comment by tykji93** [comment]
hello. is there any update?

**Comment by xiezhy6** [comment]
> hello. is there any update?

Hi, we have updated the test scripts. Now you can run the test code without the parameter '--use-sleeve-mask' if the sleeve mask is unavailable in your case.
